### ISSUE TITLE
How to get "manifest" mapping?

### ISSUE THREAD

**Issue by stereosteve** [asabil/gobble-rev#1]
Is there a way to have this plugin output a "manifest" file that maps from original filename to hashed filename?

An example from [node-rev](https://www.npmjs.com/package/node-rev):

```
{"test.css":"test-934823cbc6.css"}
```

**Comment by asabil** [comment]
Should be easy to add, will fix as soon as possible

**Comment by asabil** [comment]
Added, you can now create a manifest:

``` js
module.exports = gobble([
    html,
    styles,
    images,
    scripts
]).transform('rev', {skipRename: ['*.html'], manifest: 'manifest.json'});
```

**Comment by stereosteve** [comment]
Many thanks!
